######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 18 10:33:56 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp

RESOURCES += \
    ex-i18n.qrc
