######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 17 11:16:55 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS+=-lmysqlclient

# Input
HEADERS += ListDemo.h
SOURCES += ListDemo.cpp main.cpp
