######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 18 09:19:11 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += mainwindow.qrc
